### ISSUE TITLE
Allow php8

### ISSUE THREAD

**Issue by garak** [yohang/CalendR#60]
Please

**Comment by rrmx** [comment]
+1 
Please allow PHP8. It broke an important module of my project. 😢

**Comment by peter279k** [comment]
Just notice that it seems that this repository is inactive for about many years...

Maybe someone can fork this repository and resolve this issue and other pending issues.

I plan to do that. If some has any better ideas, please tell me :).

**Comment by rrmx** [comment]
> Just notice that it seems that this repository is inactive for about many years...
> 
> Maybe someone can fork this repository and resolve this issue and other pending issues.
> 
> I plan to do that. If some has any better ideas, please tell me :).

do it man! let me know if you need anything

**Comment by peter279k** [comment]
@garak and @rrmx, since this repository is inactive for about whiles, I forked this and update some stuffs (including resolving this issue and let this repository require `php-7.1` version at least).

And I release the [3.0.0](https://github.com/peter279k/fork-CalendR/releases/tag/3.0.0) version and publish this repository to the [Packagist.org](https://packagist.org/packages/peter279k/fork-calendr) site.

If having any issues, please submit them on this [issue URL](https://github.com/peter279k/fork-CalendR/issues). Thanks :).

**Comment by rrmx** [comment]
> @garak and @rrmx, since this repository is inactive for about whiles, I forked this and update some stuffs (including resolving this issue and let this repository require `php-7.1` version at least).
> 
> And I release the [3.0.0](https://github.com/peter279k/fork-CalendR/releases/tag/3.0.0) version and publish this repository to the [Packagist.org](https://packagist.org/packages/peter279k/fork-calendr) site.
> 
> If having any issues, please submit them on this [issue URL](https://github.com/peter279k/fork-CalendR/issues). Thanks :).

Thanks a lot Peter!
Works like a charm!
